import SearchSharpIcon from "@mui/icons-material/SearchSharp";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import LocalLaundryServiceIcon from "@mui/icons-material/LocalLaundryService";
import ShortTextIcon from "@mui/icons-material/ShortText";
import CloseIcon from "@mui/icons-material/Close";
import PeopleAltIcon from "@mui/icons-material/PeopleAlt";
import HomeIcon from "@mui/icons-material/Home";
import CallIcon from "@mui/icons-material/Call";
import HelpOutlineIcon from "@mui/icons-material/HelpOutline";
import PaymentsIcon from "@mui/icons-material/Payments";
import LibraryBooksIcon from "@mui/icons-material/LibraryBooks";
import InstagramIcon from "@mui/icons-material/Instagram";
import WifiIcon from "@mui/icons-material/Wifi";
import ConnectedTvIcon from "@mui/icons-material/ConnectedTv";
import AirportShuttleIcon from "@mui/icons-material/AirportShuttle";
import BedOutlinedIcon from "@mui/icons-material/BedOutlined";
import CleaningServicesIcon from "@mui/icons-material/CleaningServices";
import CropFreeOutlinedIcon from "@mui/icons-material/CropFreeOutlined";
import WcOutlinedIcon from "@mui/icons-material/WcOutlined";
import BathtubOutlinedIcon from "@mui/icons-material/BathtubOutlined";
import MarkEmailReadOutlinedIcon from "@mui/icons-material/MarkEmailReadOutlined";
import MaximizeOutlinedIcon from "@mui/icons-material/MaximizeOutlined";
import FiberManualRecordIcon from "@mui/icons-material/FiberManualRecord";
export const SearchSharpMuiIcon = SearchSharpIcon;
export const PlayArrowMuiIcon = PlayArrowIcon;
export const LocalLaundryServiceMuiIcon = LocalLaundryServiceIcon;
export const ShortTextMuiIcon = ShortTextIcon;
export const CloseIconMuiIcon = CloseIcon;
export const HomeIconMuiIcon = HomeIcon;
export const PeopleAltIconMuiIcon = PeopleAltIcon;
export const CallMuiIcon = CallIcon;
export const HelpOutlineIconMuiIcon = HelpOutlineIcon;
export const PaymentMuiICon = PaymentsIcon;
export const LibraryBooksIconMuiIcon = LibraryBooksIcon;
export const InstagramMuiIcon = InstagramIcon;
export const WifiMuiIcon = WifiIcon;
export const AirportShuttleMuiIcon = AirportShuttleIcon;
export const ConnectedTvMuiIcon = ConnectedTvIcon;
export const BedOutlinedMuiIcon = BedOutlinedIcon;
export const CleaningServicesMuiIcon = CleaningServicesIcon;
export const CropFreeOutlinedMuiIcon = CropFreeOutlinedIcon;
export const WcOutlinedMuiIcon = WcOutlinedIcon;
export const BathtubOutlinedMuiIcon = BathtubOutlinedIcon;
export const MarkEmailReadOutlinedMuiIcon = MarkEmailReadOutlinedIcon;
export const MaximizeOutlinedMuiIcon = MaximizeOutlinedIcon;
export const FiberManualRecordMuiIcon = FiberManualRecordIcon;
