name: Deploy

on:
  push:
    branches:
      - master  # Keeping 'master' as the default branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Updated to latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci  # Faster and more reliable for CI/CD

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # Keeping 'master' branch condition

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          branch: gh-pages  # Ensure deployment to GitHub Pages branch
